### ISSUE TITLE
Local package breaks uv2nix

### ISSUE THREAD

**Issue by daedric** [pyproject-nix/uv2nix#109]
Hi,
While porting a project from poetry2nix, I stumbled upon an issue when local package were used.
Given the following pyproject.toml

```toml
[project]
name = "data-stream"
description = ""
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
   "polaris-client",
]

[dependency-groups]
dev = [
    "pytest (>=7.3.2,<8.0.0)",
    "pytest-cov (>=4.1.0,<5.0.0)",
    "ruff (>=0.7.0,<1.0.0)",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.uv.sources]
polaris-client = { path = "libs/polaris" }
```

Running `$> nix develop .#uv2nix` raises:

```
warning: Git tree '/home/ts/work/vibe/data-stream' is dirty
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/7hw19rbs6p20l2gxbf13la04pcs2znmz-source/pkgs/stdenv/generic/make-derivation.nix:375:7

       … while evaluating attribute 'UV_PYTHON' of derivation 'nix-shell'

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'polaris-client' missing
       at /nix/store/71i8gf2xb1x1hzlc99djr94l2zh7jh5v-source/build/lib/resolvers.nix:118:23:
          117|               let
          118|                 pkg = set.${key};
             |                       ^
          119|                 dependencies = pkg.passthru.dependencies or { };
```
