### ISSUE TITLE
Attribute 'hash' missing

### ISSUE THREAD

**Issue by fromtheeast710** [pyproject-nix/uv2nix#175]
### Describe the issue
When running `nix develop`, the shell failed to initialize with the following message
```
warning: Git tree '/home/theeast/Documents/Education/WSU/CS3/ProfessionalExperience/final-system-pa2524' is dirty
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'wombot'
         whose name attribute is located at /nix/store/707m8gfbdyxhg1sgkiw5x9zh84ya012r-source/pkgs/stdenv/generic/make-derivation.nix:438:13

       … while evaluating attribute 'NIX_PYPROJECT_DEPS' of derivation 'wombot'

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'hash' missing
       at /nix/store/spz3dvi8hjhw4xdn6w89k31yr3bq40p7-source/lib/build.nix:331:45:
          330|                 name = srcFilename selectedWheel.url;
          331|                 inherit (selectedWheel) url hash;
             |                                             ^
          332|               })
```

### Additional context

`flake.nix`:
```nix
{
  outputs = inputs: with inputs;
    let
      inherit (nixpkgs) lib;

      envName = "wombot";

      workspace = uv2nix.lib.workspace.loadWorkspace { workspaceRoot = ./.; };

      overlay = workspace.mkPyprojectOverlay {
        sourcePreference = "wheel";
      };

      pyprojectOverrides = final: prev: {
        pytorch-triton-rocm = prev.pytorch-triton-rocm.overrideAttrs (old: {
          fixupPhase = ''
            export RPATH=${pkgs.zlib}:$RPATH

            runHook fixupPhase
          '';
        });
      };

      pkgs = nixpkgs.legacyPackages.x86_64-linux;

      python = pkgs.python313;

      pythonSet = (pkgs.callPackage pyproject-nix.build.packages {
        inherit python;
      }).overrideScope (
        lib.composeManyExtensions [
          pyproject-build-systems.overlays.default
          overlay
          pyprojectOverrides
        ]);
    in {
      packages.x86_64-linux.default =
        pythonSet.mkVirtualEnv envName workspace.deps.default;

      # apps.x86_64-linux = {
      #   default = {
      #     type = "app";
      #     program = "${self.packages.x86_64-linux.default}/bin/hello";
      #   };
      # };

      devShells.x86_64-linux = {
        uv2nix = let
          editableOverlay = workspace.mkEditablePyprojectOverlay {
            root = "$REPO_ROOT";
            # members = [ "hello-world" ];
          };

          editablePythonSet = pythonSet.overrideScope (
            lib.composeManyExtensions [
              editableOverlay
            ]
          );

          virtualenv =
            editablePythonSet.mkVirtualEnv (envName + "-dev") workspace.deps.all;
        in pkgs.mkShellNoCC {
          packages = [
            virtualenv
          ] ++ (with pkgs; [
            uv
          ]);

          env = {
            UV_NO_SYNC = "1";
            UV_PYTHON = "${virtualenv}/bin/python";
            UV_PYTHON_DOWNLOADS = "never";
          };

          shellHook = ''
            unset PYTHONPATH

            export REPO_ROOT=$(git rev-parse --show-toplevel)
          '';
        };
    };
  };

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    uv2nix = {
      url = "github:pyproject-nix/uv2nix";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pyproject-nix = {
      url = "github:pyproject-nix/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pyproject-build-systems = {
      url = "github:pyproject-nix/build-system-pkgs";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.uv2nix.follows = "uv2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
}
```

`pyproject.toml`:
```toml
[project]
name = "wombot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "empyrebase>=1.2.1",
    "labelme>=5.8.1",
    "lap>=0.5.12",
    "nicegui>=1.4.25",
    "ruff>=0.11.6",
    "starlette>=0.36.3",
    "torch>=2.7.0",
    "torchdata>=0.10.0",
    "torchvision>=0.21.0",
    "ultralytics>=8.3.23",
]

[tool.uv]
# prerelease = "allow"
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch = { index = "pytorch_rocm" }
torchvision = { index = "pytorch_rocm" }
torchdata = { index = "pytorch_rocm" }
request = { index = "default"}

[[tool.uv.index]]
name = "pytorch_rocm"
url = "https://download.pytorch.org/whl/rocm6.2.4"
# explicit = true
```
